/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kv_store.h"

bool_t
xdr_buf (XDR *xdrs, buf *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->buf_val, (u_int *) &objp->buf_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_kv (XDR *xdrs, kv *objp)
{
	register int32_t *buf;

	 if (!xdr_buf (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_buf (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}
