/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _KV_STORE_H_RPCGEN
#define _KV_STORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int buf_len;
	char *buf_val;
} buf;

struct kv {
	buf key;
	buf value;
};
typedef struct kv kv;

#define KVSTORE 0x20000001
#define KVSTORE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXAMPLE 1
extern  int * example_1(int *, CLIENT *);
extern  int * example_1_svc(int *, struct svc_req *);
#define ECHO 2
extern  buf * echo_1(buf *, CLIENT *);
extern  buf * echo_1_svc(buf *, struct svc_req *);
#define PUT 3
extern  void * put_1(kv *, CLIENT *);
extern  void * put_1_svc(kv *, struct svc_req *);
#define GET 4
extern  buf * get_1(buf *, CLIENT *);
extern  buf * get_1_svc(buf *, struct svc_req *);
extern int kvstore_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXAMPLE 1
extern  int * example_1();
extern  int * example_1_svc();
#define ECHO 2
extern  buf * echo_1();
extern  buf * echo_1_svc();
#define PUT 3
extern  void * put_1();
extern  void * put_1_svc();
#define GET 4
extern  buf * get_1();
extern  buf * get_1_svc();
extern int kvstore_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_buf (XDR *, buf*);
extern  bool_t xdr_kv (XDR *, kv*);

#else /* K&R C */
extern bool_t xdr_buf ();
extern bool_t xdr_kv ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_KV_STORE_H_RPCGEN */
